# fly.toml app configuration file generated for scheduler-worker on 2025-03-01
app = "shifteasy-milp-worker"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  type = "connections"
  soft_limit = 1
  hard_limit = 2
  queue = 20

[[vm]]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 4
